package net.pkhapps.nlsmap.api.codes;

import net.pkhapps.nlsmap.api.types.Language;
import net.pkhapps.nlsmap.api.types.LocalizedString;
import org.jetbrains.annotations.NotNull;

import java.util.HashMap;
import java.util.Map;
import java.util.Optional;
import java.util.stream.Stream;

/**
 * Enumeration of the municipalities in Finland.
 *
 * @see <a href="http://xml.nls.fi/Nimisto/Nimistorekisteri/kunta.xsd">kunta.xsd</a>
 */
public enum Municipality implements Code<String> {

    UNKNOWN("", "Tuntematon", "Okänd"),
    ALAJARVI("005", "Alajärvi", "Alajärvi"),
    ALAVIESKA("009", "Alavieska", "Alavieska"),
    ALAVUS("010", "Alavus", "Alavus"),
    ASIKKALA("016", "Asikkala", "Asikkala"),
    ASKOLA("018", "Askola", "Askola"),
    AURA("019", "Aura", "Aura"),
    AKAA("020", "Akaa", "Akaa"),
    BRANDO("035", "Brändö", "Brändö"),
    ECKERO("043", "Eckerö", "Eckerö"),
    ENONKOSKI("046", "Enonkoski", "Enonkoski"),
    ENONTEKIO("047", "Enontekiö", "Enontekis"),
    ESPOO("049", "Espoo", "Esbo"),
    EURA("050", "Eura", "Eura"),
    EURAJOKI("051", "Eurajoki", "Euraåminne"),
    EVIJARVI("052", "Evijärvi", "Evijärvi"),
    FINSTROM("060", "Finström", "Finström"),
    FORSSA("061", "Forssa", "Forssa"),
    FOGLO("062", "Föglö", "Föglö"),
    GETA("065", "Geta", "Geta"),
    HAAPAJARVI("069", "Haapajärvi", "Haapajärvi"),
    HAAPAVESI("071", "Haapavesi", "Haapavesi"),
    HAILUOTO("072", "Hailuoto", "Karlö"),
    HALSUA("074", "Halsua", "Halsua"),
    HAMINA("075", "Hamina", "Fredrikshamn"),
    HAMMARLAND("076", "Hammarland", "Hammarland"),
    HANKASALMI("077", "Hankasalmi", "Hankasalmi"),
    HANKO("078", "Hanko", "Hangö"),
    HARJAVALTA("079", "Harjavalta", "Harjavalta"),
    HARTOLA("081", "Hartola", "Hartola"),
    HATTULA("082", "Hattula", "Hattula"),
    HAUSJARVI("086", "Hausjärvi", "Hausjärvi"),
    HEINAVESI("090", "Heinävesi", "Heinävesi"),
    HELSINKI("091", "Helsinki", "Helsingfors"),
    VANTAA("092", "Vantaa", "Vanda"),
    HIRVENSALMI("097", "Hirvensalmi", "Hirvensalmi"),
    HOLLOLA("098", "Hollola", "Hollola"),
    HONKAJOKI("099", "Honkajoki", "Honkajoki"),
    HUITTINEN("102", "Huittinen", "Huittinen"),
    HUMPPILA("103", "Humppila", "Humppila"),
    HYRYNSALMI("105", "Hyrynsalmi", "Hyrynsalmi"),
    HYVINKAA("106", "Hyvinkää", "Hyvinge"),
    HAMEENKYRO("108", "Hämeenkyrö", "Tavastkyro"),
    HAMEENLINNA("109", "Hämeenlinna", "Tavastehus"),
    HEINOLA("111", "Heinola", "Heinola"),
    II("139", "Ii", "Ii"),
    IISALMI("140", "Iisalmi", "Idensalmi"),
    IITTI("142", "Iitti", "Iitti"),
    IKAALINEN("143", "Ikaalinen", "Ikalis"),
    ILMAJOKI("145", "Ilmajoki", "Ilmajoki"),
    ILOMANTSI("146", "Ilomantsi", "Ilomants"),
    INARI("148", "Inari", "Enare"),
    INKOO("149", "Inkoo", "Ingå"),
    ISOJOKI("151", "Isojoki", "Storå"),
    ISOKYRO("152", "Isokyrö", "Storkyro"),
    IMATRA("153", "Imatra", "Imatra"),
    JANAKKALA("165", "Janakkala", "Janakkala"),
    JOENSUU("167", "Joensuu", "Joensuu"),
    JOKIOINEN("169", "Jokioinen", "Jockis"),
    JOMALA("170", "Jomala", "Jomala"),
    JOROINEN("171", "Joroinen", "Jorois"),
    JOUTSA("172", "Joutsa", "Joutsa"),
    JUUKA("176", "Juuka", "Juuka"),
    JUUPAJOKI("177", "Juupajoki", "Juupajoki"),
    JUVA("178", "Juva", "Juva"),
    JYVASKYLA("179", "Jyväskylä", "Jyväskylä"),
    JAMIJARVI("181", "Jämijärvi", "Jämijärvi"),
    JAMSA("182", "Jämsä", "Jämsä"),
    JARVENPAA("186", "Järvenpää", "Träskända"),
    KAARINA("202", "Kaarina", "St Karins"),
    KAAVI("204", "Kaavi", "Kaavi"),
    KAJAANI("205", "Kajaani", "Kajana"),
    KALAJOKI("208", "Kalajoki", "Kalajoki"),
    KANGASALA("211", "Kangasala", "Kangasala"),
    KANGASNIEMI("213", "Kangasniemi", "Kangasniemi"),
    KANKAANPAA("214", "Kankaanpää", "Kankaanpää"),
    KANNONKOSKI("216", "Kannonkoski", "Kannonkoski"),
    KANNUS("217", "Kannus", "Kannus"),
    KARIJOKI("218", "Karijoki", "Bötom"),
    KARKKILA("224", "Karkkila", "Högfors"),
    KARSTULA("226", "Karstula", "Karstula"),
    KARVIA("230", "Karvia", "Karvia"),
    KASKINEN("231", "Kaskinen", "Kaskö"),
    KAUHAJOKI("232", "Kauhajoki", "Kauhajoki"),
    KAUHAVA("233", "Kauhava", "Kauhava"),
    KAUNIAINEN("235", "Kauniainen", "Grankulla"),
    KAUSTINEN("236", "Kaustinen", "Kaustby"),
    KEITELE("239", "Keitele", "Keitele"),
    KEMI("240", "Kemi", "Kemi"),
    KEMINMAA("241", "Keminmaa", "Keminmaa"),
    KEMPELE("244", "Kempele", "Kempele"),
    KERAVA("245", "Kerava", "Kervo"),
    KEURUU("249", "Keuruu", "Keuruu"),
    KIHNIO("250", "Kihniö", "Kihniö"),
    KINNULA("256", "Kinnula", "Kinnula"),
    KIRKKONUMMI("257", "Kirkkonummi", "Kyrkslätt"),
    KITEE("260", "Kitee", "Kitee"),
    KITTILA("261", "Kittilä", "Kittilä"),
    KIURUVESI("263", "Kiuruvesi", "Kiuruvesi"),
    KIVIJARVI("265", "Kivijärvi", "Kivijärvi"),
    KOKEMAKI("271", "Kokemäki", "Kumo"),
    KOKKOLA("272", "Kokkola", "Karleby"),
    KOLARI("273", "Kolari", "Kolari"),
    KONNEVESI("275", "Konnevesi", "Konnevesi"),
    KONTIOLAHTI("276", "Kontiolahti", "Kontiolahti"),
    KORSNAS("280", "Korsnäs", "Korsnäs"),
    KOSKI_TL("284", "Koski Tl", "Koski Tl"),
    KOTKA("285", "Kotka", "Kotka"),
    KOUVOLA("286", "Kouvola", "Kouvola"),
    KRISTIINANKAUPUNKI("287", "Kristiinankaupunki", "Kristinestad"),
    KRUUNUPYY("288", "Kruunupyy", "Kronoby"),
    KUHMO("290", "Kuhmo", "Kuhmo"),
    KUHMOINEN("291", "Kuhmoinen", "Kuhmoinen"),
    KUMLINGE("295", "Kumlinge", "Kumlinge"),
    KUOPIO("297", "Kuopio", "Kuopio"),
    KUORTANE("300", "Kuortane", "Kuortane"),
    KURIKKA("301", "Kurikka", "Kurikka"),
    KUSTAVI("304", "Kustavi", "Gustavs"),
    KUUSAMO("305", "Kuusamo", "Kuusamo"),
    OUTOKUMPU("309", "Outokumpu", "Outokumpu"),
    KYYJARVI("312", "Kyyjärvi", "Kyyjärvi"),
    KARKOLA("316", "Kärkölä", "Kärkölä"),
    KARSAMAKI("317", "Kärsämäki", "Kärsämäki"),
    KOKAR("318", "Kökar", "Kökar"),
    KEMIJARVI("320", "Kemijärvi", "Kemijärvi"),
    KEMIONSAARI("322", "Kemiönsaari", "Kimitoön"),
    LAHTI("398", "Lahti", "Lahtis"),
    LAIHIA("399", "Laihia", "Laihela"),
    LAITILA("400", "Laitila", "Laitila"),
    LAPINLAHTI("402", "Lapinlahti", "Lapinlahti"),
    LAPPAJARVI("403", "Lappajärvi", "Lappajärvi"),
    LAPPEENRANTA("405", "Lappeenranta", "Villmanstrand"),
    LAPINJARVI("407", "Lapinjärvi", "Lappträsk"),
    LAPUA("408", "Lapua", "Lappo"),
    LAUKAA("410", "Laukaa", "Laukaa"),
    LEMI("416", "Lemi", "Lemi"),
    LEMLAND("417", "Lemland", "Lemland"),
    LEMPAALA("418", "Lempäälä", "Lempäälä"),
    LEPPAVIRTA("420", "Leppävirta", "Leppävirta"),
    LESTIJARVI("421", "Lestijärvi", "Lestijärvi"),
    LIEKSA("422", "Lieksa", "Lieksa"),
    LIETO("423", "Lieto", "Lundo"),
    LIMINKA("425", "Liminka", "Limingo"),
    LIPERI("426", "Liperi", "Liperi"),
    LOIMAA("430", "Loimaa", "Loimaa"),
    LOPPI("433", "Loppi", "Loppi"),
    LOVIISA("434", "Loviisa", "Lovisa"),
    LUHANKA("435", "Luhanka", "Luhanka"),
    LUMIJOKI("436", "Lumijoki", "Lumijoki"),
    LUMPARLAND("438", "Lumparland", "Lumparland"),
    LUOTO("440", "Luoto", "Larsmo"),
    LUUMAKI("441", "Luumäki", "Luumäki"),
    LOHJA("444", "Lohja", "Lojo"),
    PARAINEN("445", "Parainen", "Pargas"),
    MAALAHTI("475", "Maalahti", "Malax"),
    MAARIANHAMINA("478", "Maarianhamina", "Mariehamn"),
    MARTTILA("480", "Marttila", "Marttila"),
    MASKU("481", "Masku", "Masku"),
    MERIJARVI("483", "Merijärvi", "Merijärvi"),
    MERIKARVIA("484", "Merikarvia", "Sastmola"),
    MIEHIKKALA("489", "Miehikkälä", "Miehikkälä"),
    MIKKELI("491", "Mikkeli", "S:t Michel"),
    MUHOS("494", "Muhos", "Muhos"),
    MULTIA("495", "Multia", "Multia"),
    MUONIO("498", "Muonio", "Muonio"),
    MUSTASAARI("499", "Mustasaari", "Korsholm"),
    MUURAME("500", "Muurame", "Muurame"),
    MYNAMAKI("503", "Mynämäki", "Mynämäki"),
    MYRSKYLA("504", "Myrskylä", "Mörskom"),
    MANTSALA("505", "Mäntsälä", "Mäntsälä"),
    MANTYHARJU("507", "Mäntyharju", "Mäntyharju"),
    MANTTA_VILPPULA("508", "Mänttä-Vilppula", "Mänttä-Vilppula"),
    NAANTALI("529", "Naantali", "Nådendal"),
    NAKKILA("531", "Nakkila", "Nakkila"),
    NIVALA("535", "Nivala", "Nivala"),
    NOKIA("536", "Nokia", "Nokia"),
    NOUSIAINEN("538", "Nousiainen", "Nousis"),
    NURMES("541", "Nurmes", "Nurmes"),
    NURMIJARVI("543", "Nurmijärvi", "Nurmijärvi"),
    NARPIO("545", "Närpiö", "Närpes"),
    ORIMATTILA("560", "Orimattila", "Orimattila"),
    ORIPAA("561", "Oripää", "Oripää"),
    ORIVESI("562", "Orivesi", "Orivesi"),
    OULAINEN("563", "Oulainen", "Oulainen"),
    OULU("564", "Oulu", "Uleåborg"),
    PADASJOKI("576", "Padasjoki", "Padasjoki"),
    PAIMIO("577", "Paimio", "Pemar"),
    PALTAMO("578", "Paltamo", "Paltamo"),
    PARIKKALA("580", "Parikkala", "Parikkala"),
    PARKANO("581", "Parkano", "Parkano"),
    PELKOSENNIEMI("583", "Pelkosenniemi", "Pelkosenniemi"),
    PERHO("584", "Perho", "Perho"),
    PERTUNMAA("588", "Pertunmaa", "Pertunmaa"),
    PETAJAVESI("592", "Petäjävesi", "Petäjävesi"),
    PIEKSAMAKI("593", "Pieksämäki", "Pieksämäki"),
    PIELAVESI("595", "Pielavesi", "Pielavesi"),
    PIETARSAARI("598", "Pietarsaari", "Jakobstad"),
    PEDERSOREN_KUNTA("599", "Pedersören kunta", "Pedersöre"),
    PIHTIPUDAS("601", "Pihtipudas", "Pihtipudas"),
    PIRKKALA("604", "Pirkkala", "Birkala"),
    POLVIJARVI("607", "Polvijärvi", "Polvijärvi"),
    POMARKKU("608", "Pomarkku", "Påmark"),
    PORI("609", "Pori", "Björneborg"),
    PORNAINEN("611", "Pornainen", "Borgnäs"),
    POSIO("614", "Posio", "Posio"),
    PUDASJARVI("615", "Pudasjärvi", "Pudasjärvi"),
    PUKKILA("616", "Pukkila", "Pukkila"),
    PUNKALAIDUN("619", "Punkalaidun", "Punkalaidun"),
    PUOLANKA("620", "Puolanka", "Puolanka"),
    PUUMALA("623", "Puumala", "Puumala"),
    PYHTAA("624", "Pyhtää", "Pyttis"),
    PYHAJOKI("625", "Pyhäjoki", "Pyhäjoki"),
    PYHAJARVI("626", "Pyhäjärvi", "Pyhäjärvi"),
    PYHANTA("630", "Pyhäntä", "Pyhäntä"),
    PYHARANTA("631", "Pyhäranta", "Pyhäranta"),
    PALKANE("635", "Pälkäne", "Pälkäne"),
    POYTYA("636", "Pöytyä", "Pöytyä"),
    PORVOO("638", "Porvoo", "Borgå"),
    RAAHE("678", "Raahe", "Brahestad"),
    RAISIO("680", "Raisio", "Reso"),
    RANTASALMI("681", "Rantasalmi", "Rantasalmi"),
    RANUA("683", "Ranua", "Ranua"),
    RAUMA("684", "Rauma", "Raumo"),
    RAUTALAMPI("686", "Rautalampi", "Rautalampi"),
    RAUTAVAARA("687", "Rautavaara", "Rautavaara"),
    RAUTJARVI("689", "Rautjärvi", "Rautjärvi"),
    REISJARVI("691", "Reisjärvi", "Reisjärvi"),
    RIIHIMAKI("694", "Riihimäki", "Riihimäki"),
    RISTIJARVI("697", "Ristijärvi", "Ristijärvi"),
    ROVANIEMI("698", "Rovaniemi", "Rovaniemi"),
    RUOKOLAHTI("700", "Ruokolahti", "Ruokolahti"),
    RUOVESI("702", "Ruovesi", "Ruovesi"),
    RUSKO("704", "Rusko", "Rusko"),
    RAAKKYLA("707", "Rääkkylä", "Rääkkylä"),
    RAASEPORI("710", "Raasepori", "Raseborg"),
    SAARIJARVI("729", "Saarijärvi", "Saarijärvi"),
    SALLA("732", "Salla", "Salla"),
    SALO("734", "Salo", "Salo"),
    SALTVIK("736", "Saltvik", "Saltvik"),
    SAUVO("738", "Sauvo", "Sagu"),
    SAVITAIPALE("739", "Savitaipale", "Savitaipale"),
    SAVONLINNA("740", "Savonlinna", "Nyslott"),
    SAVUKOSKI("742", "Savukoski", "Savukoski"),
    SEINAJOKI("743", "Seinäjoki", "Seinäjoki"),
    SIEVI("746", "Sievi", "Sievi"),
    SIIKAINEN("747", "Siikainen", "Siikainen"),
    SIIKAJOKI("748", "Siikajoki", "Siikajoki"),
    SIILINJARVI("749", "Siilinjärvi", "Siilinjärvi"),
    SIMO("751", "Simo", "Simo"),
    SIPOO("753", "Sipoo", "Sibbo"),
    SIUNTIO("755", "Siuntio", "Sjundeå"),
    SODANKYLA("758", "Sodankylä", "Sodankylä"),
    SOINI("759", "Soini", "Soini"),
    SOMERO("761", "Somero", "Somero"),
    SONKAJARVI("762", "Sonkajärvi", "Sonkajärvi"),
    SOTKAMO("765", "Sotkamo", "Sotkamo"),
    SOTTUNGA("766", "Sottunga", "Sottunga"),
    SULKAVA("768", "Sulkava", "Sulkava"),
    SUND("771", "Sund", "Sund"),
    SUOMUSSALMI("777", "Suomussalmi", "Suomussalmi"),
    SUONENJOKI("778", "Suonenjoki", "Suonenjoki"),
    SYSMA("781", "Sysmä", "Sysmä"),
    SAKYLA("783", "Säkylä", "Säkylä"),
    VAALA("785", "Vaala", "Vaala"),
    SASTAMALA("790", "Sastamala", "Sastamala"),
    SIIKALATVA("791", "Siikalatva", "Siikalatva"),
    TAIPALSAARI("831", "Taipalsaari", "Taipalsaari"),
    TAIVALKOSKI("832", "Taivalkoski", "Taivalkoski"),
    TAIVASSALO("833", "Taivassalo", "Tövsala"),
    TAMMELA("834", "Tammela", "Tammela"),
    TAMPERE("837", "Tampere", "Tammerfors"),
    TERVO("844", "Tervo", "Tervo"),
    TERVOLA("845", "Tervola", "Tervola"),
    TEUVA("846", "Teuva", "Östermark"),
    TOHMAJARVI("848", "Tohmajärvi", "Tohmajärvi"),
    TOHOLAMPI("849", "Toholampi", "Toholampi"),
    TOIVAKKA("850", "Toivakka", "Toivakka"),
    TORNIO("851", "Tornio", "Torneå"),
    TURKU("853", "Turku", "Åbo"),
    PELLO("854", "Pello", "Pello"),
    TUUSNIEMI("857", "Tuusniemi", "Tuusniemi"),
    TUUSULA("858", "Tuusula", "Tusby"),
    TYRNAVA("859", "Tyrnävä", "Tyrnävä"),
    ULVILA("886", "Ulvila", "Ulvsby"),
    URJALA("887", "Urjala", "Urjala"),
    UTAJARVI("889", "Utajärvi", "Utajärvi"),
    UTSJOKI("890", "Utsjoki", "Utsjoki"),
    UURAINEN("892", "Uurainen", "Uurainen"),
    UUSIKAARLEPYY("893", "Uusikaarlepyy", "Nykarleby"),
    UUSIKAUPUNKI("895", "Uusikaupunki", "Nystad"),
    VAASA("905", "Vaasa", "Vasa"),
    VALKEAKOSKI("908", "Valkeakoski", "Valkeakoski"),
    VALTIMO("911", "Valtimo", "Valtimo"),
    VARKAUS("915", "Varkaus", "Varkaus"),
    VEHMAA("918", "Vehmaa", "Vehmaa"),
    VESANTO("921", "Vesanto", "Vesanto"),
    VESILAHTI("922", "Vesilahti", "Vesilahti"),
    VETELI("924", "Veteli", "Vetil"),
    VIEREMA("925", "Vieremä", "Vieremä"),
    VIHTI("927", "Vihti", "Vichtis"),
    VIITASAARI("931", "Viitasaari", "Viitasaari"),
    VIMPELI("934", "Vimpeli", "Vimpeli"),
    VIROLAHTI("935", "Virolahti", "Virolahti"),
    VIRRAT("936", "Virrat", "Virdois"),
    VARDO("941", "Vårdö", "Vårdö"),
    VOYRI("946", "Vöyri", "Vörå"),
    YLITORNIO("976", "Ylitornio", "Övertorneå"),
    YLIVIESKA("977", "Ylivieska", "Ylivieska"),
    YLOJARVI("980", "Ylöjärvi", "Ylöjärvi"),
    YPAJA("981", "Ypäjä", "Ypäjä"),
    AHTARI("989", "Ähtäri", "Etseri"),
    AANEKOSKI("992", "Äänekoski", "Äänekoski");

    private static final Map<String, Municipality> codeMap = new HashMap<>();

    static {
        Stream.of(values()).forEach(code -> codeMap.put(code.code, code));
    }

    private final String code;
    private final LocalizedString name;

    Municipality(String code, String nameFin, String nameSwe) {
        this.code = code;
        this.name = LocalizedString.builder()
                .withValue(Language.FINNISH, nameFin)
                .withValue(Language.SWEDISH, nameSwe)
                .build();
    }

    /**
     * Returns the municipality with the given code.
     */
    public static @NotNull Optional<Municipality> findByCode(@NotNull String code) {
        return Optional.ofNullable(codeMap.get(code));
    }

    /**
     * Returns the name of the municipality.
     */
    public @NotNull LocalizedString getName() {
        return name;
    }

    @Override
    public @NotNull String getCode() {
        return code;
    }

    @Override
    public @NotNull LocalizedString getDescription() {
        return name;
    }
}
